

[workspace]
members = ["src/*"]
resolver = "3"


[workspace.dependencies]
log = "0.4.22"
test-log = "0.2.16"


[profile.test]
debug = "none"
strip = "debuginfo"
lto = "fat"
codegen-units = 1
opt-level = 3
panic = "abort"
overflow-checks = false
debug-assertions = false
